services:
  openfishh:
    build: .
    container_name: openfishh
    ports:
      - "3000:3000"
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
