import { useState, useEffect, useRef } from 'react'
import ReactMarkdown from 'react-markdown'
import { FileText, Search, BookOpen, Brain, Zap, CheckCircle, Download } from 'lucide-react'
import jsPDF from 'jspdf'

const QUERY = 'What are the current cyber threats targeting financial institutions?'

const REPORT_MD = `# Cyber Threats Targeting Financial Institutions

*37 claims from 12 sources. Most recent evidence: 4 hours ago.*

---

## Executive Summary

The financial sector is experiencing a significant escalation in cyber threats, driven by the convergence of state-sponsored operations and increasingly sophisticated criminal infrastructure. IRGC-linked threat actors have explicitly threatened US technology and defense companies, while the Lazarus Group continues to target banking systems through social engineering at an industrial scale. The discovery of CVE-2026-33579 in widely-deployed authentication middleware has created a new attack surface that remains actively exploited.

The primary risk is the compounding effect of simultaneous threats: nation-state actors, zero-day vulnerabilities, and supply-chain compromise are converging on financial infrastructure at a pace that outstrips most institutions' detection capabilities. Recommended action: prioritize patching CVE-2026-33579, implement hardware-backed authentication tokens, and assume breach posture for any system touching SWIFT or cross-border payment rails.

## 1. Nation-State Threat Escalation

The Iran-US conflict has moved from kinetic to cyber domains with direct implications for financial institutions. IRGC cyber units have expanded their target set beyond traditional military and energy infrastructure to include major US financial technology firms, a shift confirmed by multiple intelligence streams. The AtlasCross RAT, attributed to Iranian-aligned operators, has been detected in networks of at least three G-SIB institutions, exploiting procedural vulnerabilities in interbank transfer authorization.

## 2. Supply Chain and Zero-Day Exposure

CVE-2026-33579 represents the most critical vulnerability currently affecting the financial sector. The flaw exists in a permission model used by over 4,000 financial applications globally, allowing privilege escalation through malformed authentication tokens. Active exploitation has been confirmed by Ukrainian CERT-UA, with attack chains originating from compromised CI/CD pipelines.

## 3. Criminal Infrastructure Evolution

The Lazarus Group's March 2026 operation against Bangladesh Bank demonstrated a shift from brute-force attacks to precision social engineering. Five targeted emails compromised an entire institution's SWIFT access. This operational model is being replicated across Southeast Asian banking networks.

---

## What Would Change Our Mind

- **Iran IRGC threatens US tech firms**: Would be invalidated if US-Iran ceasefire is reached and IRGC cyber operations demonstrably cease
- **CVE-2026-33579 is actively exploited**: Would weaken if major vendors release patches and exploitation rate drops below baseline
- **Lazarus Group targets financial institutions**: Would be falsified if attribution is revised by CISA or the group shifts to non-financial targets

## Known Unknowns

- 3 claims are based on social media discussion, not primary reporting
- 2 claims are predictions, not verified facts
- No wire service sources were found for CVE-2026-33579 exploitation claims

## Evidence & Sources

**Claim Quality**: 8 Supported, 12 Tentative, 5 Speculative

**Source Tiers**: Specialist Trade (7), Social (4), Institutional (1)

**Cited Sources**:
- [krebsonsecurity.com](https://krebsonsecurity.com) -- Specialist Trade
- [darkreading.com](https://www.darkreading.com) -- Specialist Trade
- [thehackernews.com](https://thehackernews.com) -- Specialist Trade
- [reddit.com](https://reddit.com) -- Social

---

*Generated by OpenFishh Blueprint Engine. 37 claims evaluated across 12 sources. Epistemic health: B grade.*`

const WORKFLOW_STEPS = [
  { action: 'search', label: 'Searching web', detail: '12 results from 8 sources', tool: 'Tavily Search', duration: 2.3 },
  { action: 'fetch', label: 'Fetching articles', detail: '5 full articles retrieved', tool: 'Web Reader', duration: 3.1 },
  { action: 'extract', label: 'Extracting claims', detail: '37 claims with epistemic metadata', tool: 'Claim Extractor', duration: 4.8 },
  { action: 'section', label: 'Writing Executive Summary', detail: 'Synthesizing top findings', tool: 'Report Writer', duration: 2.1 },
  { action: 'section', label: 'Writing threat analysis', detail: '3 threat sections', tool: 'Report Writer', duration: 3.7 },
  { action: 'section', label: 'Generating falsification criteria', detail: 'What Would Change Our Mind', tool: 'Falsification Engine', duration: 1.2 },
  { action: 'section', label: 'Auditing sources', detail: 'Evidence & known unknowns', tool: 'Source Auditor', duration: 0.9 },
  { action: 'complete', label: 'Report complete', detail: '37 claims, 12 sources', tool: null, duration: 0 },
]

const TOOL_ICONS = { search: Search, fetch: BookOpen, extract: Brain, section: FileText, complete: CheckCircle }

function isMobile() { return window.innerWidth <= 640 }

export default function ReportStep({ data, onComplete, completed }) {
  const [phase, setPhase] = useState(completed ? 'done' : 'idle')
  const [visibleChars, setVisibleChars] = useState(completed ? REPORT_MD.length : 0)
  const [timelineOpen, setTimelineOpen] = useState(!completed)
  const [visibleSteps, setVisibleSteps] = useState(completed ? WORKFLOW_STEPS.length : 0)
  const [elapsed, setElapsed] = useState(completed ? 18.1 : 0)
  const reportRef = useRef(null)
  const abortRef = useRef(null)

  async function generate() {
    const ctrl = new AbortController()
    abortRef.current = ctrl
    const s = ctrl.signal

    setPhase('generating')
    let totalElapsed = 0

    // First 3 steps: search, fetch, extract
    for (let i = 0; i < 3; i++) {
      const step = WORKFLOW_STEPS[i]
      setVisibleSteps(i + 1)
      totalElapsed += step.duration
      setElapsed(Math.round(totalElapsed * 10) / 10)
      await delay(1200 + Math.random() * 600, s); if (s.aborted) return
    }

    // Writing steps: type out report progressively
    setVisibleSteps(4)
    totalElapsed += WORKFLOW_STEPS[3].duration
    setElapsed(Math.round(totalElapsed * 10) / 10)
    setPhase('typing')

    const totalChars = REPORT_MD.length
    const chunkSize = 50
    for (let i = 0; i < totalChars; i += chunkSize) {
      setVisibleChars(Math.min(i + chunkSize, totalChars))
      await delay(12, s); if (s.aborted) return
      if (reportRef.current) reportRef.current.scrollTop = reportRef.current.scrollHeight

      // Update workflow steps at section boundaries
      const progress = i / totalChars
      if (progress > 0.35 && visibleSteps < 5) { setVisibleSteps(5); totalElapsed += WORKFLOW_STEPS[4].duration; setElapsed(Math.round(totalElapsed * 10) / 10) }
      if (progress > 0.7 && visibleSteps < 6) { setVisibleSteps(6); totalElapsed += WORKFLOW_STEPS[5].duration; setElapsed(Math.round(totalElapsed * 10) / 10) }
      if (progress > 0.88 && visibleSteps < 7) { setVisibleSteps(7); totalElapsed += WORKFLOW_STEPS[6].duration; setElapsed(Math.round(totalElapsed * 10) / 10) }
    }

    setVisibleSteps(8)
    setElapsed(18.1)
    await delay(400, s); if (s.aborted) return
    setPhase('done')
    if (isMobile()) setTimelineOpen(false)
    if (reportRef.current) reportRef.current.scrollTop = 0
  }

  // Track visibleSteps in a ref so the typing loop can read it
  const visibleStepsRef = useRef(visibleSteps)
  useEffect(() => { visibleStepsRef.current = visibleSteps }, [visibleSteps])
  // Expose for the typing loop
  Object.defineProperty(generate, '_visibleSteps', { get: () => visibleStepsRef.current })

  useEffect(() => {
    return () => { if (abortRef.current) abortRef.current.abort() }
  }, [])

  function downloadPDF() {
    const pdf = new jsPDF('p', 'mm', 'a4')
    const margin = 18
    const pageW = pdf.internal.pageSize.getWidth() - margin * 2
    const pageH = pdf.internal.pageSize.getHeight() - margin * 2
    let y = margin

    function checkPage(needed) {
      if (y + needed > margin + pageH) { pdf.addPage(); y = margin }
    }

    // Parse markdown lines and render
    const lines = REPORT_MD.split('\n')
    for (const line of lines) {
      const trimmed = line.trim()
      if (!trimmed) { y += 3; continue }

      if (trimmed.startsWith('# ')) {
        checkPage(14)
        pdf.setFont('helvetica', 'bold').setFontSize(18).setTextColor(20, 20, 20)
        pdf.text(trimmed.slice(2), margin, y)
        y += 10
      } else if (trimmed.startsWith('## ')) {
        checkPage(12)
        y += 4
        pdf.setFont('helvetica', 'bold').setFontSize(13).setTextColor(40, 40, 40)
        pdf.text(trimmed.slice(3), margin, y)
        y += 8
      } else if (trimmed.startsWith('---')) {
        checkPage(6)
        y += 2
        pdf.setDrawColor(200).setLineWidth(0.3)
        pdf.line(margin, y, margin + pageW, y)
        y += 4
      } else if (trimmed.startsWith('- ')) {
        checkPage(6)
        const text = trimmed.slice(2).replace(/\*\*/g, '').replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
        pdf.setFont('helvetica', 'normal').setFontSize(10).setTextColor(60, 60, 60)
        const wrapped = pdf.splitTextToSize('  ' + text, pageW - 4)
        wrapped.forEach(wl => { checkPage(5); pdf.text(wl, margin + 4, y); y += 4.5 })
        y += 1
      } else if (trimmed.startsWith('*') && trimmed.endsWith('*') && !trimmed.startsWith('**')) {
        checkPage(6)
        pdf.setFont('helvetica', 'italic').setFontSize(9).setTextColor(120, 120, 120)
        const text = trimmed.replace(/\*/g, '')
        const wrapped = pdf.splitTextToSize(text, pageW)
        wrapped.forEach(wl => { checkPage(4.5); pdf.text(wl, margin, y); y += 4 })
        y += 2
      } else {
        checkPage(5)
        const text = trimmed.replace(/\*\*/g, '').replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
        pdf.setFont('helvetica', 'normal').setFontSize(10).setTextColor(50, 50, 50)
        const wrapped = pdf.splitTextToSize(text, pageW)
        wrapped.forEach(wl => { checkPage(4.5); pdf.text(wl, margin, y); y += 4.5 })
        y += 2
      }
    }

    // Footer on each page
    const totalPages = pdf.internal.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i)
      pdf.setFont('helvetica', 'normal').setFontSize(7).setTextColor(160)
      pdf.text('Generated by OpenFishh Blueprint Engine', margin, pdf.internal.pageSize.getHeight() - 8)
      pdf.text(`Page ${i} of ${totalPages}`, pdf.internal.pageSize.getWidth() - margin - 20, pdf.internal.pageSize.getHeight() - 8)
    }

    pdf.save('OpenFishh-Blueprint-Report.pdf')
  }

  const visibleReport = REPORT_MD.slice(0, visibleChars)

  return (
    <div style={{ padding: 24 }}>
      {/* Query */}
      <div style={{
        padding: '14px 18px', marginBottom: 16, borderRadius: 10,
        border: '1px solid rgba(255,255,255,0.06)',
        background: 'rgba(255,255,255,0.02)',
      }}>
        <div style={{ fontSize: '0.6rem', color: '#0EA5E9', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 }}>
          Blueprint Query
        </div>
        <div style={{ fontSize: '0.95rem', fontWeight: 600, color: '#fff', lineHeight: 1.4 }}>
          {QUERY}
        </div>
      </div>

      {/* Main split layout */}
      <div className="report-split" style={{ display: 'flex', gap: 16, minHeight: 480 }}>
        <style>{`
          @media (max-width: 640px) {
            .report-split { flex-direction: column-reverse !important; min-height: auto !important; }
            .report-split .report-timeline { width: 100% !important; max-height: none !important; }
            .report-split .report-content { max-height: 60vh !important; }
          }
        `}</style>

        {/* LEFT: Report -- white bg, continuous document */}
        <div className="report-content" style={{ flex: 1, minWidth: 0 }}>
          {/* Download bar */}
          {phase === 'done' && (
            <div style={{
              display: 'flex', justifyContent: 'flex-end', marginBottom: 8,
            }}>
              <button onClick={downloadPDF} style={{
                display: 'flex', alignItems: 'center', gap: 6,
                padding: '5px 14px', borderRadius: 6,
                border: '1px solid rgba(255,255,255,0.1)',
                background: 'transparent', color: '#888',
                fontSize: '0.72rem', fontWeight: 500, cursor: 'pointer',
              }}>
                <Download style={{ width: 13, height: 13 }} /> Download PDF
              </button>
            </div>
          )}

          <div ref={reportRef} style={{
            overflow: 'auto', maxHeight: phase === 'done' ? 'calc(100vh - 380px)' : 'calc(100vh - 340px)',
            borderRadius: 10, border: '1px solid rgba(0,0,0,0.08)',
            background: '#fff',
            padding: phase === 'idle' ? 0 : '28px 32px',
            boxShadow: '0 1px 4px rgba(0,0,0,0.04)',
          }}>
            {phase === 'idle' ? (
              <div style={{ height: 480, display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#fafafa' }}>
                <div style={{ textAlign: 'center' }}>
                  <FileText style={{ width: 32, height: 32, color: '#ccc', marginBottom: 12 }} />
                  <div style={{ color: '#999', fontSize: '0.85rem' }}>Click below to generate a Blueprint report</div>
                </div>
              </div>
            ) : (
              <ReactMarkdown components={{
                h1: ({ children }) => <h1 style={{ fontSize: '1.25rem', fontWeight: 700, color: '#1D1D1F', margin: '0 0 4px', letterSpacing: '-0.02em', fontFamily: "'Inter', system-ui, sans-serif" }}>{children}</h1>,
                h2: ({ children }) => <h2 style={{ fontSize: '0.95rem', fontWeight: 600, color: '#1D1D1F', margin: '28px 0 8px', fontFamily: "'Inter', system-ui, sans-serif" }}>{children}</h2>,
                p: ({ children }) => <p style={{ fontSize: '0.82rem', lineHeight: 1.75, color: '#424245', margin: '0 0 12px' }}>{children}</p>,
                strong: ({ children }) => <strong style={{ color: '#1D1D1F', fontWeight: 600 }}>{children}</strong>,
                em: ({ children }) => <em style={{ color: '#86868B' }}>{children}</em>,
                li: ({ children }) => <li style={{ fontSize: '0.8rem', color: '#424245', lineHeight: 1.65, marginBottom: 4 }}>{children}</li>,
                a: ({ href, children }) => <a href={href} style={{ color: '#0969DA', textDecoration: 'none' }}>{children}</a>,
                hr: () => <hr style={{ border: 'none', borderTop: '1px solid #E5E5EA', margin: '24px 0' }} />,
              }}>
                {visibleReport}
              </ReactMarkdown>
            )}
          </div>
        </div>

        {/* RIGHT: Workflow timeline */}
        <div className="report-timeline" style={{
          width: 240, flexShrink: 0, overflow: 'auto',
          maxHeight: 'calc(100vh - 340px)',
        }}>
          {/* Mobile toggle header */}
          {phase !== 'idle' && (
            <div className="show-mobile-only" onClick={() => setTimelineOpen(prev => !prev)} style={{
              display: 'none', /* shown via media query */
              alignItems: 'center', justifyContent: 'space-between',
              padding: '10px 14px', marginBottom: 8, borderRadius: 8,
              border: '1px solid rgba(255,255,255,0.06)',
              background: 'rgba(255,255,255,0.02)', cursor: 'pointer',
            }}>
              <span style={{ fontSize: '0.72rem', fontWeight: 600, color: '#aaa' }}>
                Workflow {phase === 'done' ? 'Complete' : 'Progress'}
              </span>
              <span style={{ fontSize: '0.72rem', color: '#555', transform: timelineOpen ? 'rotate(180deg)' : 'rotate(0)', transition: 'transform 0.2s' }}>&#9662;</span>
            </div>
          )}
          <style>{`@media (max-width: 640px) { .show-mobile-only { display: flex !important; } }`}</style>

          {/* Metrics */}
          {phase !== 'idle' && timelineOpen && (
            <div style={{
              padding: '12px 14px', marginBottom: 12, borderRadius: 8,
              border: '1px solid rgba(255,255,255,0.06)',
              background: 'rgba(255,255,255,0.02)',
              display: 'flex', flexWrap: 'wrap', gap: '8px 16px',
            }}>
              <MiniStat label="Elapsed" value={`${elapsed}s`} />
              <MiniStat label="Claims" value="37" />
              <MiniStat label="Sources" value="12" />
              <div>
                <span style={{
                  fontSize: '0.6rem', fontWeight: 600,
                  padding: '2px 8px', borderRadius: 4,
                  background: phase === 'done' ? 'rgba(16,185,129,0.1)' : 'rgba(245,158,11,0.1)',
                  color: phase === 'done' ? '#10B981' : '#F59E0B',
                  border: `1px solid ${phase === 'done' ? 'rgba(16,185,129,0.2)' : 'rgba(245,158,11,0.2)'}`,
                }}>
                  {phase === 'done' ? 'Complete' : 'Generating'}
                </span>
              </div>
            </div>
          )}

          {/* Timeline */}
          <div style={{ display: timelineOpen ? 'block' : 'none' }}>
            {WORKFLOW_STEPS.slice(0, visibleSteps).map((step, i) => {
              const Icon = TOOL_ICONS[step.action] || Zap
              const isActive = i === visibleSteps - 1 && phase !== 'done'
              const isDone = i < visibleSteps - 1 || phase === 'done'

              return (
                <div key={i} style={{ display: 'flex', gap: 10, marginBottom: 2 }}>
                  <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', width: 14 }}>
                    <div style={{
                      width: 8, height: 8, borderRadius: '50%', flexShrink: 0,
                      background: isDone ? '#10B981' : isActive ? '#F59E0B' : '#333',
                      boxShadow: isActive ? '0 0 6px rgba(245,158,11,0.4)' : 'none',
                    }} />
                    {i < WORKFLOW_STEPS.length - 1 && (
                      <div style={{
                        width: 1, flex: 1, minHeight: 20,
                        background: isDone ? 'rgba(16,185,129,0.3)' : 'rgba(255,255,255,0.06)',
                      }} />
                    )}
                  </div>
                  <div style={{ paddingBottom: 10, flex: 1 }}>
                    <div style={{ fontSize: '0.7rem', fontWeight: 600, color: isDone ? '#ccc' : isActive ? '#fff' : '#666', marginBottom: 1 }}>
                      {step.label}
                    </div>
                    <div style={{ fontSize: '0.6rem', color: '#555' }}>{step.detail}</div>
                    {step.tool && (
                      <div style={{
                        display: 'inline-flex', alignItems: 'center', gap: 4,
                        marginTop: 3, padding: '1px 6px', borderRadius: 3,
                        background: 'rgba(255,255,255,0.04)', fontSize: '0.55rem', color: '#555',
                      }}>
                        <Icon style={{ width: 9, height: 9 }} />
                        {step.tool}
                        {step.duration > 0 && <span style={{ color: '#444', fontFamily: "'JetBrains Mono', monospace" }}>{step.duration}s</span>}
                      </div>
                    )}
                  </div>
                </div>
              )
            })}

            {phase !== 'idle' && phase !== 'done' && visibleSteps < WORKFLOW_STEPS.length && (
              <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
                <div style={{ width: 14, display: 'flex', justifyContent: 'center' }}>
                  <div style={{ width: 6, height: 6, borderRadius: '50%', background: '#333', animation: 'pulse 1.5s infinite' }} />
                  <style>{`@keyframes pulse { 50% { opacity: 0.3 } }`}</style>
                </div>
                <span style={{ fontSize: '0.6rem', color: '#444' }}>Processing...</span>
              </div>
            )}
          </div>

          {phase === 'idle' && timelineOpen && (
            <div style={{ textAlign: 'center', padding: '40px 12px' }}>
              <Zap style={{ width: 16, height: 16, color: '#333', marginBottom: 8 }} />
              <div style={{ fontSize: '0.65rem', color: '#444' }}>Workflow timeline appears during generation</div>
            </div>
          )}
        </div>
      </div>

      {/* Action */}
      <div style={{ marginTop: 20, display: 'flex', gap: 12 }}>
        {phase === 'idle' && (
          <button onClick={generate} style={{
            display: 'flex', alignItems: 'center', gap: 8,
            padding: '10px 24px', borderRadius: 8, border: 'none',
            background: '#0EA5E9', color: '#fff',
            fontSize: '0.85rem', fontWeight: 600, cursor: 'pointer',
          }}>
            <FileText style={{ width: 16, height: 16 }} /> Generate Report
          </button>
        )}
        {phase === 'done' && (
          <button onClick={onComplete} style={{
            padding: '10px 24px', borderRadius: 8, border: 'none',
            background: '#10B981', color: '#fff',
            fontSize: '0.85rem', fontWeight: 600, cursor: 'pointer',
          }}>
            Continue to Exploration
          </button>
        )}
      </div>
      <style>{`@keyframes spin { to { transform: rotate(360deg) } }`}</style>
    </div>
  )
}

function MiniStat({ label, value }) {
  return (
    <div>
      <div style={{ fontSize: '0.55rem', color: '#555' }}>{label}</div>
      <div style={{ fontSize: '0.78rem', fontWeight: 600, color: '#fff', fontFamily: "'JetBrains Mono', monospace" }}>{value}</div>
    </div>
  )
}

function delay(ms, signal) {
  return new Promise((resolve) => {
    if (signal?.aborted) { resolve(); return }
    const id = setTimeout(resolve, ms)
    signal?.addEventListener('abort', () => { clearTimeout(id); resolve() }, { once: true })
  })
}
